server:
  port: 8870  #服务端口
spring:

  profiles:
    active: dev #环境配置
  application:
    name: service-core #服务名
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minio2022_db?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 配置文件上传大小限制
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
#    host: 192.168.100.100
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/maple/srb/core/mapper/xml/*.xml
  mapper-locations: classpath*:/mapper/*Mapper.xml


# 设置日志级别
#logging:
#  level:
#    root: ERROR

#minio 文件服务配置
minio:
  enable: true  # 必须配置 true
  enableHttps: false # 是否使用https
#  endpoint: http://192.168.50.249:9000
  endpoint: http://192.168.0.105:9000
  #  endpoint: http://192.168.0.104:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: demo1